<a href="https://colab.research.google.com/github/porwoj/python-ml/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tworzenie tablic

In [1]:
print('Hello Colab')

Hello Colab


In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

Array 1D

In [5]:
x = np.array([1, 3])

In [6]:
x, print(x )

[1 3]


(array([1, 3]), None)

In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [13]:
y = np.array([1.3,2.3,1.4])

In [14]:
y.dtype

dtype('float64')

In [16]:
z = np.array([[1, 2],[-3, 1]])

In [17]:
z.ndim

2

In [18]:
z.shape

(2, 2)

In [20]:
z1 = np.array([[1,2,4],[4,2,1,]])

In [21]:
z1.shape

(2, 3)

In [22]:
z1.ndim

2

In [27]:
d3 = np.array([
    [
      [4, 3, 1],
      [3, 1, 2]
    ],
    [
      [4, 1, 3],
      [3, 1, 2]
    ],
    [
       [3, 2, 1],
       [4, 3, 2]
    ]
]
)

In [28]:
d3.shape

(3, 2, 3)

In [29]:
d3.ndim

3

## Typy Danych

In [30]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [31]:
B = np.array([1.0, 2.3,3.3])
B.dtype

dtype('float64')

In [32]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [40]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [38]:
A = np.array([1.0, 2.3, 3.3], dtype='int')
A.dtype
A

array([1, 2, 3])

In [41]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-43-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [44]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

## Tworzenie tablic 2

In [49]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
np.full(shape=(3, 3), fill_value=5, dtype='int')

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [55]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [57]:
np.arange(start=0, stop=2, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95])

In [59]:
np.linspace(start=0, stop=1, num=100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [60]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
A.reshape((5, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
A.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [64]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Podstawowe informacje o tablocach

In [65]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [66]:
A + B

array([6, 0, 7, 4])

In [67]:
B - A

array([ 0, -2, -1,  0])

In [68]:
A * B

array([ 9, -1, 12,  4])

In [69]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [70]:
A + 3

array([6, 4, 7, 5])

In [71]:
A - 2

array([ 1, -1,  2,  0])

In [73]:
A * 1.2

array([3.6, 1.2, 4.8, 2.4])

In [74]:
A + 3 * B

array([12, -2, 13,  8])

In [75]:
np.add(A,B)

array([6, 0, 7, 4])

In [86]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y, '\n')

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]] 



In [81]:
X * Y

array([[6, 0],
       [2, 0]])

In [82]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [83]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [84]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [85]:
X @ Y

array([[  3,   6],
       [-12,   0]])

##Generowanie liczb pseudolosowych

In [87]:
np.random.seed(0)

In [88]:
np.random.randn()

1.764052345967664

In [89]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [90]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [91]:
np.random.rand()

0.1965823616800535

In [92]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [93]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [94]:
np.random.randint(10)

3

In [96]:
np.random.randint(low=10, high=101)

56

In [97]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [98]:
np.random.choice([3,6,2,9,2])

3

In [99]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [100]:
dat = np.arange(10)
dat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.random.shuffle(dat)
dat
np.random.shuffle(dat)
dat

array([5, 3, 1, 4, 9, 0, 6, 7, 2, 8])

##Podstawowe funkcje

In [3]:
np.exp(2)

7.38905609893065

In [4]:
np.sqrt(4)

2.0

In [6]:
np.all([2, 3, 1, 0])

False

In [7]:
np.any([0, 0, 1, 0])

True

In [8]:
bool(1.5)

True

In [9]:
bool(-2)

True

In [13]:
A = np.random.rand(5)
A


array([0.86465445, 0.55528972, 0.12471319, 0.72549108, 0.6369115 ])

In [14]:
np.argmax(A)

0

In [15]:
np.argmin(A)

2

In [16]:
np.argsort(A)

array([2, 1, 4, 3, 0])

In [17]:
np.max(A)

0.8646544532701406

In [18]:
np.min(A)

0.1247131936529744

In [19]:
np.mean(A)

0.581411990693607

In [20]:
np.median(A)

0.6369115015779919

In [21]:
np.std(A)

0.250328359308119

##Indeksowanie i wycinanie

In [22]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
A[0]

0

In [34]:
A[[4,6,7]]

array([4, 6, 7])

In [35]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
A[3]

array([15, 16, 17, 18, 19])

In [38]:
A[:,-2]

array([ 3,  8, 13, 18])

In [39]:
A[1,3]

8

In [42]:
A[1:2,0:4]

array([[5, 6, 7, 8]])

In [43]:
A[2:,3:]

array([[13, 14],
       [18, 19]])

In [44]:
A[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [45]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
A[2,3] = 44
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [33, 33, 33, 44, 33],
       [15, 16, 17, 18, 19]])

##Iteracja po tablicach

In [49]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[33 33 33 44 33]
[15 16 17 18 19]


In [55]:
for row in A:
  for cell in row:
    print(cell,end=" ")
  print('\n')

0 1 2 3 4 

5 6 7 8 9 

33 33 33 44 33 

15 16 17 18 19 



In [56]:
for row in A.flat:
  print(row)

0
1
2
3
4
5
6
7
8
9
33
33
33
44
33
15
16
17
18
19


In [57]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 33, 33],
       [33, 44, 33, 15],
       [16, 17, 18, 19]])

In [58]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 33, 33, 33, 44, 33, 15, 16,
       17, 18, 19])

In [60]:
A.T

array([[ 0,  5, 33, 15],
       [ 1,  6, 33, 16],
       [ 2,  7, 33, 17],
       [ 3,  8, 44, 18],
       [ 4,  9, 33, 19]])

In [72]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [73]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
np.bitwise_and(A > -3, A < 2.5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [78]:
A[np.bitwise_and(A > -3, A < 2.5)]

array([-2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [79]:
A[np.bitwise_or(A > -3, A < 2.5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])